#!/bin/bash
# =====================================================================
# E3 — Ablations of FedSTEP (algo fedpart_be), CIFAR-10, 40xRPi-4, alpha=1,
# E=8, T=200, lr=0.003, measured cost. Two parts:
#   (A) FULL M x T_r GRID: M in {2,3,4} x T_r in {2,3,4}  (rotation always on)
#   (B) mechanism ablations at the default (M=4, T_r=3): no rotation (T_r=0),
#       no representation-proximal term (mu_repr=0).
# Configs are generated by sed from the E1 base (configs/e1_main.yaml).
# Out: results/E3/M<M>_Tr<Tr>/seed<S>/ and results/E3/{no_rotation,no_repr}/seed<S>/
#
# Usage:  bash scripts/run_e3.sh        # SEEDS / M_LIST / TR_LIST env-overridable
# =====================================================================
set -u
cd "$(dirname "${BASH_SOURCE[0]}")/.."
PY=venv/bin/python
BASE=configs/e1_main.yaml          # M=4, T_r=3, lr=0.003, CIFAR-10, RPi-4, E=8
SEEDS="${SEEDS:-42 43 44}"
M_LIST="${M_LIST:-2 3 4}"
TR_LIST="${TR_LIST:-2 3 4}"

mk_cfg() {  # $1=num_tiers $2=rotation_period [$3=mu_repr] -> stdout file $4
  if [ -n "${3:-}" ]; then MUR="s/^    mu_repr: .*/    mu_repr: $3/"; else MUR=""; fi
  sed -e "s/^    num_tiers: .*/    num_tiers: $1/" \
      -e "s/^    rotation_period: .*/    rotation_period: $2/" \
      ${MUR:+-e "$MUR"} "$BASE" > "$4"
}

run() {  # $1=config $2=outdir $3=logtag $4=seed
  echo "===== E3 $3 seed$4 START $(date) ====="
  caffeinate -si $PY run_experiment.py --config "$1" --algo fedpart_be \
      --seed "$4" --output "$2" --cost-model measured --device mps \
      > "/tmp/e3_$3_s$4.log" 2>&1 || echo "  FAILED rc=$? (/tmp/e3_$3_s$4.log)"
}

for S in $SEEDS; do
  # (A) M x T_r grid
  for M in $M_LIST; do
    for TR in $TR_LIST; do
      mk_cfg "$M" "$TR" "" "/tmp/e3_M${M}_Tr${TR}.yaml"
      run "/tmp/e3_M${M}_Tr${TR}.yaml" "results/E3/M${M}_Tr${TR}/seed${S}" "M${M}_Tr${TR}" "$S"
    done
  done
  # (B) mechanism ablations (default M=4, T_r=3)
  mk_cfg 4 0 ""    /tmp/e3_no_rotation.yaml
  run /tmp/e3_no_rotation.yaml "results/E3/no_rotation/seed${S}" no_rotation "$S"
  mk_cfg 4 3 0.0  /tmp/e3_no_repr.yaml
  run /tmp/e3_no_repr.yaml     "results/E3/no_repr/seed${S}"     no_repr     "$S"
done

echo "===== E3 AGGREGATE (mean +/- std over seeds) ====="
for M in $M_LIST; do for TR in $TR_LIST; do
  echo "## M=$M T_r=$TR"; $PY scripts/aggregate_seeds.py "results/E3/M${M}_Tr${TR}" 2>/dev/null || true
done; done
for V in no_rotation no_repr; do
  echo "## $V"; $PY scripts/aggregate_seeds.py "results/E3/$V" 2>/dev/null || true
done
