#!/usr/bin/env bash
# Phase-2 DMD campaigns on a local machine, GPU by default.
#   scripts/run_phase2_local.sh [dataset] [device] [pool] [threads] [experiment]
#   scripts/run_phase2_local.sh fashionmnist mps 4 2 bounded_margin   # the defaults
#   scripts/run_phase2_local.sh fashionmnist mps 4 2 cbce_margin
#
# Four stages; the experiments are documented in scripts/gen_emnist_phase2.py:
#   1. 2a: mean_mu sweep of the calibrated arms, plus the reference arm when the
#      experiment has one, on the calibration partitions;
#   2. each arm's mean_mu fixed by the criterion in gen_emnist_phase2.select;
#   3. 2b configs generated with those intensities;
#   4. 2b: every arm on the disjoint test partitions x inits.
# Relaunch any time: finished runs are skipped and the selection is recomputed
# from the same calibration runs. Do not edit this file while it runs: bash
# reads a script as it executes it and would resume mid-line in the new text.
set -euo pipefail
DATASET="${1:-fashionmnist}"; DEVICE="${2:-mps}"; POOL="${3:-4}"; THREADS="${4:-2}"
EXPERIMENT="${5:-bounded_margin}"

# Partition seeds whose smallest client cannot hold 500 train + 150 anchors are
# replaced by the next feasible ones (gen_emnist_phase2.feasible_partitions).
GEN=(python3 scripts/gen_emnist_phase2.py --dataset "$DATASET"
     --experiment "$EXPERIMENT" --feasible-partitions)
paths=$("${GEN[@]}" --step describe)
read -r CONFIGS CAL_RESULTS TEST_RESULTS LOGTAG N_CALIBRATED <<< "$paths"
if [ -z "${N_CALIBRATED:-}" ]; then
  echo "could not resolve the campaign paths for ${EXPERIMENT}" >&2
  exit 1
fi
PROGRESS="logs/${LOGTAG}/_progress.txt"
mkdir -p "logs/${LOGTAG}"
export FEDLAB_NUM_WORKERS=0
# A calibration name ends its arm with the swept value (_mu0.3, _b0.99, _t1) right
# before _p, a test name ends its arm with a letter: the two globs never overlap.
CAL_GLOB="${CONFIGS}/*[0-9]_p[0-9]*_i[0-9]*.yaml"
TEST_GLOB="${CONFIGS}/*[a-z]_p[0-9]*_i[0-9]*.yaml"

note() { echo "$(date +%H:%M:%S) === $*" | tee -a "$PROGRESS"; }

# Keep the Mac from idle-sleeping for as long as this script runs. Closing the
# lid still sleeps it and pauses every run.
if command -v caffeinate > /dev/null; then
  caffeinate -i -w $$ &
fi

# Download once up front: concurrent first runs would race on the same files.
python3 -c "
from datasets.registry import _load_raw_dataset
for split in ('train', 'test'):
    _load_raw_dataset('${DATASET}', split, './data')
"

note "${EXPERIMENT} ${DATASET} on ${DEVICE}, pool=${POOL} threads=${THREADS}"

# Generated configs are wiped before each generation so a seed dropped by the
# feasibility rule, or an intensity no longer selected, is not rerun.
rm -f $TEST_GLOB
if [ "$N_CALIBRATED" -gt 0 ]; then
  note "stage 1/4: 2a mean_mu sweep"
  rm -f $CAL_GLOB
  generated=$("${GEN[@]}" --device "$DEVICE" --step calibrate)
  echo "$generated" | sed -n 1p | tee -a "$PROGRESS"
  scripts/run_campaign.sh "$CAL_GLOB" "$CAL_RESULTS" "$LOGTAG" "$POOL" "$THREADS"

  note "stage 2/4: intensity selection"
  selection=$("${GEN[@]}" --step select)
  echo "$selection" | tee -a "$PROGRESS"

  note "stage 3/4: 2b configs"
  generated=$("${GEN[@]}" --device "$DEVICE" --step test \
    --selection "${CONFIGS}/phase2a_selection.json")
else
  note "stages 1-3 skipped: every arm has a fixed mean_mu"
  generated=$("${GEN[@]}" --device "$DEVICE" --step test)
fi
echo "$generated" | sed -n 1p | tee -a "$PROGRESS"

note "stage 4/4: 2b test"
scripts/run_campaign.sh "$TEST_GLOB" "$TEST_RESULTS" "$LOGTAG" "$POOL" "$THREADS"

done_count=$(find "logs/${LOGTAG}" -name '*.done' | wc -l | tr -d ' ')
total=$(find "$CONFIGS" -name '*.yaml' | wc -l | tr -d ' ')
note "${EXPERIMENT} DONE: ${done_count}/${total} runs"
